services:
  app:
    build: .
    container_name: flask_app
    expose:
      - "5000"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

  tor:
    image: goldy/tor-hidden-service:latest
    container_name: tor_hidden_service
    links:
      - nginx
    #depends_on:
    #  - nginx
    environment:
      #VIRTUAL_PORT: 80
      #HIDDEN_SERVICE_PORTS: 80:nginx:80
      SERVICE1_TOR_SERVICE_HOSTS: "80:nginx:80"
      SERVICE1_TOR_SERVICE_VERSION: '3'
      SERVICE1_TOR_SERVICE_KEY: |
        PT0gZWQyNTUxOXYxLXNlY3JldDogdHlwZTAgPT0AAAAo16QfN6dliJbXpt6dkjJ9AbRQFNAPcsYN1fL564MnWUmd76/CE5hWmiW88r1v1E/tBDR2uQot7HuquCdNsGu9
    volumes:
      - ./hidden_service:/var/lib/tor/hidden_service
    restart: unless-stopped
